#define string0 NSLocalizedString(@"Diving Equipment",@"POI type with osm tags: shop = dive")
#define string1 NSLocalizedString(@"Public Toilets",@"POI type with osm tags: amenity = toilets")
#define string2 NSLocalizedString(@"Boutique",@"POI type with osm tags: shop = boutique")
#define string3 NSLocalizedString(@"Veterinary",@"POI type with osm tags: amenity = veterinary")
#define string4 NSLocalizedString(@"Christian Cemetery",@"POI type with osm tags: religion = christian, landuse = cemetery")
#define string5 NSLocalizedString(@"Shopping Mall",@"POI type with osm tags: shop = mall")
#define string6 NSLocalizedString(@"Tactile Map",@"Optional value with osm value: tactile_map")
#define string7 NSLocalizedString(@"Seventh Day Adventist",@"Optional value with osm value: seventh_day_adventist")
#define string8 NSLocalizedString(@"Dam",@"Optional value with osm value: dam")
#define string9 NSLocalizedString(@"Tower Type",@"Optional tag with osm key: tower:type")
#define string10 NSLocalizedString(@"Glass",@"Optional tag with osm key: recycling:glass")
#define string11 NSLocalizedString(@"Thrermometer",@"Optional tag with osm key: thermometer")
#define string12 NSLocalizedString(@"Water Tower",@"POI type with osm tags: man_made = water_tower")
#define string13 NSLocalizedString(@"Animal Boarding",@"POI type with osm tags: amenity = animal_boarding")
#define string14 NSLocalizedString(@"Wired",@"Optional value with osm value: wired")
#define string15 NSLocalizedString(@"Tourism",@"Title For Category")
#define string16 NSLocalizedString(@"Microbrewery",@"Optional tag with osm key: microbrewery")
#define string17 NSLocalizedString(@"Region",@"Optional value with osm value: region")
#define string18 NSLocalizedString(@"Car Parts Store",@"POI type with osm tags: shop = car_parts")
#define string19 NSLocalizedString(@"Post Box",@"POI type with osm tags: amenity = post_box")
#define string20 NSLocalizedString(@"Karaite",@"Optional value with osm value: karaite")
#define string21 NSLocalizedString(@"Theme Park",@"POI type with osm tags: tourism = theme_park")
#define string22 NSLocalizedString(@"Outdoor Seating",@"Optional tag with osm key: outdoor_seating")
#define string23 NSLocalizedString(@"Athletics",@"Optional value with osm value: athletics")
#define string24 NSLocalizedString(@"Newsstand ",@"POI type with osm tags: shop = newsagent")
#define string25 NSLocalizedString(@"Ruins",@"POI type with osm tags: historic = ruins")
#define string26 NSLocalizedString(@"Antique",@"Optional value with osm value: antiquarian")
#define string27 NSLocalizedString(@"Coffee Shop",@"Optional value with osm value: coffee_shop")
#define string28 NSLocalizedString(@"Hiking",@"Optional tag with osm key: hiking")
#define string29 NSLocalizedString(@"Tents",@"Optional tag with osm key: tents")
#define string30 NSLocalizedString(@"Mural",@"Optional value with osm value: mural")
#define string31 NSLocalizedString(@"Toy Store",@"POI type with osm tags: shop = toys")
#define string32 NSLocalizedString(@"humanistic",@"Optional value with osm value: Humanistic")
#define string33 NSLocalizedString(@"United Church of Christ",@"Optional value with osm value: united_church_of_christ")
#define string34 NSLocalizedString(@"Cuisine",@"Optional tag with osm key: cuisine")
#define string35 NSLocalizedString(@"Multifaith",@"POI type with osm tags: religion = multifaith, amenity = place_of_worship")
#define string36 NSLocalizedString(@"Recycling Container",@"POI type with osm tags: amenity = recycling, recycling_type = container")
#define string37 NSLocalizedString(@"Wall Mounted",@"Optional value with osm value: wall_mounted")
#define string38 NSLocalizedString(@"Antiques",@"POI type with osm tags: shop = antiques")
#define string39 NSLocalizedString(@"State",@"Optional tag with osm key: addr:state")
#define string40 NSLocalizedString(@"Hockey",@"Optional value with osm value: hockey")
#define string41 NSLocalizedString(@"Ref",@"Optional tag with osm key: ref")
#define string42 NSLocalizedString(@"Car Sharing",@"POI type with osm tags: amenity = car_sharing")
#define string43 NSLocalizedString(@"Water Park",@"POI type with osm tags: leisure = water_park")
#define string44 NSLocalizedString(@"Homeless Shelter",@"POI type with osm tags: amenity = social_facility, social_facility = shelter, social_facility:for = homeless")
#define string45 NSLocalizedString(@"Orthodox",@"Optional value with osm value: orthodox")
#define string46 NSLocalizedString(@"Bicycles Sold",@"Optional tag with osm key: service:bicycle:retail")
#define string47 NSLocalizedString(@"Fire Station",@"POI type with osm tags: amenity = fire_station")
#define string48 NSLocalizedString(@"Hardware Store",@"POI type with osm tags: shop = hardware")
#define string49 NSLocalizedString(@"Pub",@"POI type with osm tags: amenity = pub")
#define string50 NSLocalizedString(@"Waterfall",@"POI type with osm tags: waterway = waterfall")
#define string51 NSLocalizedString(@"Bicycle Parking",@"POI type with osm tags: amenity = bicycle_parking")
#define string52 NSLocalizedString(@"Defensive",@"Optional value with osm value: defensive")
#define string53 NSLocalizedString(@"Entertainment and Art",@"Title For Category")
#define string54 NSLocalizedString(@"Hydro",@"Optional value with osm value: hydro")
#define string55 NSLocalizedString(@"Pagan",@"POI type with osm tags: religion = pagan, amenity = place_of_worship")
#define string56 NSLocalizedString(@"General Store",@"POI type with osm tags: shop = general")
#define string57 NSLocalizedString(@"Information Board",@"POI type with osm tags: information = board, tourism = information")
#define string58 NSLocalizedString(@"Plants",@"Optional value with osm value: plants")
#define string59 NSLocalizedString(@"Province",@"Optional tag with osm key: addr:province")
#define string60 NSLocalizedString(@"Drive In",@"Optional tag with osm key: drive_in")
#define string61 NSLocalizedString(@"Car Repair",@"POI type with osm tags: shop = car_repair")
#define string62 NSLocalizedString(@"Gasoline",@"Optional value with osm value: gasoline")
#define string63 NSLocalizedString(@"Cricket",@"Optional value with osm value: cricket")
#define string64 NSLocalizedString(@"Greek",@"Optional value with osm value: greek")
#define string65 NSLocalizedString(@"Book Store",@"POI type with osm tags: shop = books")
#define string66 NSLocalizedString(@"Green",@"Optional value with osm value: green")
#define string67 NSLocalizedString(@"Faces",@"Optional tag with osm key: faces")
#define string68 NSLocalizedString(@"Bell Tower",@"Optional value with osm value: bell_tower")
#define string69 NSLocalizedString(@"Power Substation",@"POI type with osm tags: power = generator")
#define string70 NSLocalizedString(@"Nautical Craft Wreck",@"POI type with osm tags: historic = wreck")
#define string71 NSLocalizedString(@"Kebab",@"Optional value with osm value: kebab")
#define string72 NSLocalizedString(@"Communication",@"Optional value with osm value: communication")
#define string73 NSLocalizedString(@"Alaouite",@"Optional value with osm value: alaouite")
#define string74 NSLocalizedString(@"Camp Site",@"POI type with osm tags: tourism = camp_site")
#define string75 NSLocalizedString(@"Children",@"Optional value with osm value: children")
#define string76 NSLocalizedString(@"Ismaili",@"Optional value with osm value: ismaili")
#define string77 NSLocalizedString(@"Arts Center",@"POI type with osm tags: amenity = arts_centre")
#define string78 NSLocalizedString(@"Voltage",@"Optional tag with osm key: voltage")
#define string79 NSLocalizedString(@"Spanish",@"Optional value with osm value: spanish")
#define string80 NSLocalizedString(@"Alternative",@"Optional value with osm value: alternative")
#define string81 NSLocalizedString(@"Gas Station",@"POI type with osm tags: amenity = fuel")
#define string82 NSLocalizedString(@"Doctor",@"POI type with osm tags: amenity = doctors")
#define string83 NSLocalizedString(@"Hindu",@"Optional value with osm value: hindu")
#define string84 NSLocalizedString(@"Support",@"Optional tag with osm key: support")
#define string85 NSLocalizedString(@"Candy Shop",@"POI type with osm tags: shop = confectionery")
#define string86 NSLocalizedString(@"Fountain",@"POI type with osm tags: amenity = fountain")
#define string87 NSLocalizedString(@"Free",@"Optional value with osm value: free")
#define string88 NSLocalizedString(@"Lean-to",@"Optional value with osm value: lean-to")
#define string89 NSLocalizedString(@"Customers",@"Optional value with osm value: customers")
#define string90 NSLocalizedString(@"Emergency Phone",@"POI type with osm tags: emergency = phone")
#define string91 NSLocalizedString(@"Hut",@"POI type with osm tags: building = hut")
#define string92 NSLocalizedString(@"Flagpole",@"POI type with osm tags: man_made = flagpole")
#define string93 NSLocalizedString(@"Senior Assisted Living",@"POI type with osm tags: amenity = social_facility, social_facility = assisted_living, social_facility:for = senior")
#define string94 NSLocalizedString(@"Baseball",@"Optional value with osm value: baseball")
#define string95 NSLocalizedString(@"Peak",@"POI type with osm tags: natural = peak")
#define string96 NSLocalizedString(@"Statue",@"Optional value with osm value: statue")
#define string97 NSLocalizedString(@"Mosaic",@"Optional value with osm value: mosaic")
#define string98 NSLocalizedString(@"Subway Station",@"POI type with osm tags: subway = yes, public_transport = station")
#define string99 NSLocalizedString(@"Korean",@"Optional value with osm value: korean")
#define string100 NSLocalizedString(@"Driving School",@"POI type with osm tags: amenity = driving_school")
#define string101 NSLocalizedString(@"Painting",@"Optional value with osm value: painting")
#define string102 NSLocalizedString(@"Bicycle Rental/Share",@"POI type with osm tags: amenity = bicycle_rental")
#define string103 NSLocalizedString(@"Currency Exchange",@"POI type with osm tags: amenity = bureau_de_change")
#define string104 NSLocalizedString(@"German",@"Optional value with osm value: german")
#define string105 NSLocalizedString(@"Library",@"POI type with osm tags: amenity = library")
#define string106 NSLocalizedString(@"Pentecostal",@"Optional value with osm value: pentecostal")
#define string107 NSLocalizedString(@"Scientologist",@"POI type with osm tags: religion = scientologist, amenity = place_of_worship")
#define string108 NSLocalizedString(@"Ground",@"Optional value with osm value: ground")
#define string109 NSLocalizedString(@"Vietnamese",@"Optional value with osm value: vietnamese")
#define string110 NSLocalizedString(@"Motel",@"POI type with osm tags: tourism = motel")
#define string111 NSLocalizedString(@"Digital",@"Optional value with osm value: digital")
#define string112 NSLocalizedString(@"Scheme",@"Optional value with osm value: scheme")
#define string113 NSLocalizedString(@"Food Court",@"POI type with osm tags: amenity = food_court")
#define string114 NSLocalizedString(@"Kindergarden",@"POI type with osm tags: amenity = kindergarten")
#define string115 NSLocalizedString(@"Deli",@"POI type with osm tags: shop = deli")
#define string116 NSLocalizedString(@"Bus Station",@"POI type with osm tags: bus = yes, public_transport = station")
#define string117 NSLocalizedString(@"Wave",@"Optional value with osm value: wave")
#define string118 NSLocalizedString(@"Fusion",@"Optional value with osm value: fusion")
#define string119 NSLocalizedString(@"Modern Orthodox",@"Optional value with osm value: modern_orthodox")
#define string120 NSLocalizedString(@"Pizza",@"Optional value with osm value: pizza")
#define string121 NSLocalizedString(@"Route Ref",@"Optional tag with osm key: route_ref")
#define string122 NSLocalizedString(@"Beer Garden",@"POI type with osm tags: amenity = biergarten")
#define string123 NSLocalizedString(@"Jewelry Store",@"POI type with osm tags: shop = jewelry")
#define string124 NSLocalizedString(@"Computer Store",@"POI type with osm tags: shop = computer")
#define string125 NSLocalizedString(@"Nightclub",@"POI type with osm tags: amenity = nightclub")
#define string126 NSLocalizedString(@"Hasidic",@"Optional value with osm value: Hasidic")
#define string127 NSLocalizedString(@"Motorcycle Parking",@"POI type with osm tags: amenity = motorcycle_parking")
#define string128 NSLocalizedString(@"Department Store",@"POI type with osm tags: shop = department_store")
#define string129 NSLocalizedString(@"Taoist",@"Optional value with osm value: taoist")
#define string130 NSLocalizedString(@"Backcountry",@"Optional tag with osm key: backcountry")
#define string131 NSLocalizedString(@"Shia",@"Optional value with osm value: shia")
#define string132 NSLocalizedString(@"Japanese",@"Optional value with osm value: japanese")
#define string133 NSLocalizedString(@"Social Center",@"POI type with osm tags: amenity = social_centre")
#define string134 NSLocalizedString(@"Sundial",@"Optional value with osm value: sundial")
#define string135 NSLocalizedString(@"Beverage Shop",@"POI type with osm tags: shop = beverages")
#define string136 NSLocalizedString(@"Basic Hut",@"Optional value with osm value: basic_hut")
#define string137 NSLocalizedString(@"Alliance",@"Optional value with osm value: alliance")
#define string138 NSLocalizedString(@"Historic Battlefield",@"POI type with osm tags: historic = battlefield")
#define string139 NSLocalizedString(@"Outdoors and Natural",@"Title For Category")
#define string140 NSLocalizedString(@"Train Platform",@"POI type with osm tags: train = yes, public_transport = platform")
#define string141 NSLocalizedString(@"Open-fire",@"Optional tag with osm key: openfire")
#define string142 NSLocalizedString(@"Furniture Store",@"POI type with osm tags: shop = furniture")
#define string143 NSLocalizedString(@"Vending Machine",@"POI type with osm tags: amenity = vending_machine")
#define string144 NSLocalizedString(@"Paint Store",@"POI type with osm tags: shop = paint")
#define string145 NSLocalizedString(@"Multi-Sport",@"Optional value with osm value: multi")
#define string146 NSLocalizedString(@"Lockers",@"Optional value with osm value: lockers")
#define string147 NSLocalizedString(@"Subway Entrance",@"POI type with osm tags: railway = subway_entrance")
#define string148 NSLocalizedString(@"Italian",@"Optional value with osm value: italian")
#define string149 NSLocalizedString(@"Ibadi",@"Optional value with osm value: ibadi")
#define string150 NSLocalizedString(@"Nursing Home",@"POI type with osm tags: amenity = nursing_home")
#define string151 NSLocalizedString(@"Bar",@"POI type with osm tags: amenity = bar")
#define string152 NSLocalizedString(@"Surveillance Camera",@"POI type with osm tags: surveillance:type = camera, man_made = surveillance")
#define string153 NSLocalizedString(@"Music Store",@"POI type with osm tags: shop = music")
#define string154 NSLocalizedString(@"Gift Shop",@"POI type with osm tags: shop = gift")
#define string155 NSLocalizedString(@"Architect",@"POI type with osm tags: office = architect")
#define string156 NSLocalizedString(@"Tower",@"POI type with osm tags: man_made = tower")
#define string157 NSLocalizedString(@"Laundromat",@"POI type with osm tags: shop = laundry")
#define string158 NSLocalizedString(@"Power Generator",@"POI type with osm tags: power = generator")
#define string159 NSLocalizedString(@"Barometer",@"Optional tag with osm key: barometer")
#define string160 NSLocalizedString(@"Liberal",@"Optional value with osm value: liberal")
#define string161 NSLocalizedString(@"Food Bank",@"POI type with osm tags: amenity = social_facility, social_facility = food_bank")
#define string162 NSLocalizedString(@"Pole",@"Optional value with osm value: pole")
#define string163 NSLocalizedString(@"Sport",@"Optional tag with osm key: sport")
#define string164 NSLocalizedString(@"Biofuel",@"Optional value with osm value: biofuel")
#define string165 NSLocalizedString(@"Food and Drink",@"Title For Category")
#define string166 NSLocalizedString(@"Museum",@"POI type with osm tags: tourism = museum")
#define string167 NSLocalizedString(@"NGO",@"POI type with osm tags: office = ngo")
#define string168 NSLocalizedString(@"Butcher",@"POI type with osm tags: shop = butcher")
#define string169 NSLocalizedString(@"Accountant",@"POI type with osm tags: office = accountant")
#define string170 NSLocalizedString(@"Greek Catholic",@"Optional value with osm value: greek_catholic")
#define string171 NSLocalizedString(@"Highway Rest Area (no fuel)",@"POI type with osm tags: highway = rest_area")
#define string172 NSLocalizedString(@"Assemblies of God",@"Optional value with osm value: assemblies_of_god")
#define string173 NSLocalizedString(@"Fitness Center/Gym",@"POI type with osm tags: leisure = sports_centre")
#define string174 NSLocalizedString(@"Presbyterian",@"Optional value with osm value: presbyterian")
#define string175 NSLocalizedString(@"Chalet",@"POI type with osm tags: tourism = chalet")
#define string176 NSLocalizedString(@"Convenience Store",@"POI type with osm tags: shop = convenience")
#define string177 NSLocalizedString(@"Train Station",@"POI type with osm tags: train = yes, public_transport = station")
#define string178 NSLocalizedString(@"Dry Cleaning",@"POI type with osm tags: shop = dry_cleaning")
#define string179 NSLocalizedString(@"Pyrolysis",@"Optional value with osm value: Pyrolysis")
#define string180 NSLocalizedString(@"Seafood",@"Optional value with osm value: seafood")
#define string181 NSLocalizedString(@"Separated",@"Optional value with osm value: separated")
#define string182 NSLocalizedString(@"Observation",@"Optional value with osm value: observation")
#define string183 NSLocalizedString(@"University",@"POI type with osm tags: amenity = university")
#define string184 NSLocalizedString(@"Ultra Orthodox",@"Optional value with osm value: ultra_orthodox")
#define string185 NSLocalizedString(@"Architecture",@"Optional value with osm value: architecture")
#define string186 NSLocalizedString(@"Bus Stop",@"POI type with osm tags: bus = yes, public_transport = platform")
#define string187 NSLocalizedString(@"Shoe Store",@"POI type with osm tags: shop = shoes")
#define string188 NSLocalizedString(@"Batteries",@"Optional tag with osm key: recycling:batteries")
#define string189 NSLocalizedString(@"Embassy",@"POI type with osm tags: amenity = embassy")
#define string190 NSLocalizedString(@"Power Station",@"POI type with osm tags: power = generator")
#define string191 NSLocalizedString(@"Cafe",@"POI type with osm tags: amenity = cafe")
#define string192 NSLocalizedString(@"Motorcycle Dealership",@"POI type with osm tags: shop = motorcycle")
#define string193 NSLocalizedString(@"ATM",@"Optional tag with osm key: atm")
#define string194 NSLocalizedString(@"XXX/Adult Store",@"POI type with osm tags: shop = erotic")
#define string195 NSLocalizedString(@"Neo Orthodox",@"Optional value with osm value: neo_orthodox")
#define string196 NSLocalizedString(@"Indian",@"Optional value with osm value: indian")
#define string197 NSLocalizedString(@"Fire Hydrant",@"POI type with osm tags: emergency = fire_hydrant")
#define string198 NSLocalizedString(@"Website",@"Optional tag with osm key: website")
#define string199 NSLocalizedString(@"Transportation",@"Title For Category")
#define string200 NSLocalizedString(@"Taxi Stand",@"POI type with osm tags: amenity = taxi")
#define string201 NSLocalizedString(@"Nature",@"Optional value with osm value: nature")
#define string202 NSLocalizedString(@"Outreach",@"POI type with osm tags: amenity = social_facility, social_facility = outreach")
#define string203 NSLocalizedString(@"Date",@"Optional tag with osm key: date")
#define string204 NSLocalizedString(@"Sunni",@"Optional value with osm value: sunni")
#define string205 NSLocalizedString(@"Evangelical",@"Optional value with osm value: evangelical")
#define string206 NSLocalizedString(@"Office Building",@"POI type with osm tags: office = government")
#define string207 NSLocalizedString(@"Internet Fee",@"Optional tag with osm key: internet_access:fee")
#define string208 NSLocalizedString(@"Fish and Chips",@"Optional value with osm value: fish_and_chips")
#define string209 NSLocalizedString(@"Outdoor Store",@"POI type with osm tags: shop = outdoor")
#define string210 NSLocalizedString(@"Anaerobic Digestion",@"Optional value with osm value: anaerobic_digestion")
#define string211 NSLocalizedString(@"Road",@"Optional value with osm value: lane")
#define string212 NSLocalizedString(@"History",@"Optional value with osm value: history")
#define string213 NSLocalizedString(@"Dormitory",@"POI type with osm tags: building = dormitory")
#define string214 NSLocalizedString(@"Emergency Siren",@"POI type with osm tags: emergency = siren")
#define string215 NSLocalizedString(@"Only",@"Optional value with osm value: only")
#define string216 NSLocalizedString(@"Bicycles Cleaned",@"Optional tag with osm key: service:bicycle:cleaning")
#define string217 NSLocalizedString(@"Pet Store",@"POI type with osm tags: shop = pet")
#define string218 NSLocalizedString(@"Public Telephone",@"POI type with osm tags: amenity = telephone")
#define string219 NSLocalizedString(@"Container",@"Optional value with osm value: container")
#define string220 NSLocalizedString(@"Second Hand Store",@"POI type with osm tags: shop = second_hand")
#define string221 NSLocalizedString(@"Other",@"Title For Category")
#define string222 NSLocalizedString(@"Post Code",@"Optional tag with osm key: addr:postcode")
#define string223 NSLocalizedString(@"Soccer",@"Optional value with osm value: soccer")
#define string224 NSLocalizedString(@"Baby Hatch",@"POI type with osm tags: amenity = baby_hatch")
#define string225 NSLocalizedString(@"Craft Brewery",@"POI type with osm tags: craft = bewery")
#define string226 NSLocalizedString(@"Oil",@"Optional value with osm value: oil")
#define string227 NSLocalizedString(@"Christian",@"Optional value with osm value: christian")
#define string228 NSLocalizedString(@"Crêpes",@"Optional value with osm value: crepe")
#define string229 NSLocalizedString(@"Jewish",@"Optional value with osm value: jewish")
#define string230 NSLocalizedString(@"Highway Rest Area (fuel)",@"POI type with osm tags: highway = services")
#define string231 NSLocalizedString(@"Military Fort",@"POI type with osm tags: historic = fort")
#define string232 NSLocalizedString(@"Spa or Nail Salon",@"POI type with osm tags: shop = beauty")
#define string233 NSLocalizedString(@"Bank",@"POI type with osm tags: amenity = bank")
#define string234 NSLocalizedString(@"Art Store",@"POI type with osm tags: shop = art")
#define string235 NSLocalizedString(@"Optician",@"POI type with osm tags: shop = optician")
#define string236 NSLocalizedString(@"Charcoal",@"Optional value with osm value: charcoal")
#define string237 NSLocalizedString(@"Ahmadiya",@"Optional value with osm value: ahmadiya")
#define string238 NSLocalizedString(@"Samaritan",@"Optional value with osm value: samaritan")
#define string239 NSLocalizedString(@"Humidity",@"Optional tag with osm key: hygrometer")
#define string240 NSLocalizedString(@"Dispensing",@"Optional tag with osm key: dispensing")
#define string241 NSLocalizedString(@"Spiritualist",@"POI type with osm tags: religion = spiritualist, amenity = place_of_worship")
#define string242 NSLocalizedString(@"Biking",@"Optional tag with osm key: bicycle")
#define string243 NSLocalizedString(@"Cumbustion",@"Optional value with osm value: combustion")
#define string244 NSLocalizedString(@"Recording Studio",@"POI type with osm tags: amenity = studio")
#define string245 NSLocalizedString(@"Audio Guide",@"Optional value with osm value: audioguide")
#define string246 NSLocalizedString(@"Amusement Park",@"POI type with osm tags: tourism = theme_park")
#define string247 NSLocalizedString(@"Generic Recycling",@"POI type with osm tags: amenity = recycling")
#define string248 NSLocalizedString(@"Sikh",@"Optional value with osm value: sikh")
#define string249 NSLocalizedString(@"Stands",@"Optional value with osm value: stands")
#define string250 NSLocalizedString(@"Renewal",@"Optional value with osm value: renewal")
#define string251 NSLocalizedString(@"Moravian",@"Optional value with osm value: moravian")
#define string252 NSLocalizedString(@"Religion",@"Optional tag with osm key: religion")
#define string253 NSLocalizedString(@"Reconstructionist",@"Optional value with osm value: reconstructionist")
#define string254 NSLocalizedString(@"Waste",@"Optional value with osm value: waste")
#define string255 NSLocalizedString(@"Musical Instrument Store",@"POI type with osm tags: shop = musical_instruments")
#define string256 NSLocalizedString(@"Windmill",@"POI type with osm tags: man_made = windmill")
#define string257 NSLocalizedString(@"Tourism Information Office",@"POI type with osm tags: information = office, tourism = information")
#define string258 NSLocalizedString(@"Muslim",@"Optional value with osm value: muslim")
#define string259 NSLocalizedString(@"French",@"Optional value with osm value: french")
#define string260 NSLocalizedString(@"Subway Platform",@"POI type with osm tags: subway = yes, public_transport = platform")
#define string261 NSLocalizedString(@"Solar",@"Optional value with osm value: solar")
#define string262 NSLocalizedString(@"Services",@"Title For Category")
#define string263 NSLocalizedString(@"Clothes",@"Optional tag with osm key: recycling:clothes")
#define string264 NSLocalizedString(@"Bowling Alley (10 pin)",@"POI type with osm tags: sport = 10pin")
#define string265 NSLocalizedString(@"Progressive",@"Optional value with osm value: progressive")
#define string266 NSLocalizedString(@"Electric Vehicle Charging",@"POI type with osm tags: amenity = ev_charging")
#define string267 NSLocalizedString(@"Baby Goods",@"POI type with osm tags: shop = baby_goods")
#define string268 NSLocalizedString(@"Wheelchair",@"Optional tag with osm key: wheelchair")
#define string269 NSLocalizedString(@"Wifi",@"Optional tag with osm key: wifi")
#define string270 NSLocalizedString(@"Ice Cream Shop",@"POI type with osm tags: amenity = ice_cream")
#define string271 NSLocalizedString(@"Coal",@"Optional value with osm value: coal")
#define string272 NSLocalizedString(@"Picnic Shelter",@"Optional value with osm value: picnic_shelter")
#define string273 NSLocalizedString(@"Golf",@"Optional value with osm value: golf")
#define string274 NSLocalizedString(@"Greengrocer",@"POI type with osm tags: shop = greengrocer")
#define string275 NSLocalizedString(@"Conservative",@"Optional value with osm value: conservative")
#define string276 NSLocalizedString(@"Scenic Viewpoint",@"POI type with osm tags: tourism = viewpoint")
#define string277 NSLocalizedString(@"Display",@"Optional tag with osm key: display")
#define string278 NSLocalizedString(@"Swimming",@"Optional value with osm value: swimming")
#define string279 NSLocalizedString(@"Osmotic",@"Optional value with osm value: osmotic")
#define string280 NSLocalizedString(@"Mountain Hut",@"POI type with osm tags: tourism = apine_hut")
#define string281 NSLocalizedString(@"IT Specialist",@"POI type with osm tags: office = it")
#define string282 NSLocalizedString(@"Train Station (legacy)",@"POI type with osm tags: railway = station, train = yes, public_transport = station")
#define string283 NSLocalizedString(@"Public Transport",@"Optional value with osm value: public_transport")
#define string284 NSLocalizedString(@"Weather Shelter",@"Optional value with osm value: weather_shelter")
#define string285 NSLocalizedString(@"Mediterranean",@"Optional value with osm value: mediterranean")
#define string286 NSLocalizedString(@"Stripclub",@"POI type with osm tags: amenity = stripclub")
#define string287 NSLocalizedString(@"Christian Scientist",@"Optional value with osm value: christ_scientist")
#define string288 NSLocalizedString(@"Education",@"Title For Category")
#define string289 NSLocalizedString(@"Recycling Center",@"POI type with osm tags: amenity = recycling, recycling_type = centre")
#define string290 NSLocalizedString(@"Shinto",@"Optional value with osm value: shinto")
#define string291 NSLocalizedString(@"Police Station",@"POI type with osm tags: amenity = police")
#define string292 NSLocalizedString(@"Courthouse",@"POI type with osm tags: amenity = courthouse")
#define string293 NSLocalizedString(@"Hospital",@"POI type with osm tags: amenity = hospital")
#define string294 NSLocalizedString(@"Wikipedia",@"Optional tag with osm key: wikipedia")
#define string295 NSLocalizedString(@"Zoo",@"POI type with osm tags: tourism = zoo")
#define string296 NSLocalizedString(@"Tattoo Parlor",@"POI type with osm tags: shop = tattoo")
#define string297 NSLocalizedString(@"Source",@"Optional tag with osm key: source")
#define string298 NSLocalizedString(@"Covered",@"Optional tag with osm key: covered")
#define string299 NSLocalizedString(@"Tram Stop",@"POI type with osm tags: tram = yes, railway = tram_stop, public_transport = platform")
#define string300 NSLocalizedString(@"Shopping",@"Title For Category")
#define string301 NSLocalizedString(@"Garden Center",@"POI type with osm tags: shop = garden_centre")
#define string302 NSLocalizedString(@"Shelter",@"Optional tag with osm key: shelter")
#define string303 NSLocalizedString(@"Fax #",@"Optional tag with osm key: fax")
#define string304 NSLocalizedString(@"Pumping",@"Optional value with osm value: pumping")
#define string305 NSLocalizedString(@"Thai",@"Optional value with osm value: thai")
#define string306 NSLocalizedString(@"Barbecue/BBQ",@"POI type with osm tags: amenity = bbq")
#define string307 NSLocalizedString(@"Bus Station (legacy)",@"POI type with osm tags: amenity = bus_station")
#define string308 NSLocalizedString(@"Notice",@"Optional value with osm value: notice")
#define string309 NSLocalizedString(@"Clothing Store",@"POI type with osm tags: shop = clothes")
#define string310 NSLocalizedString(@"Tree",@"Optional value with osm value: tree")
#define string311 NSLocalizedString(@"Sporting Goods Store",@"POI type with osm tags: shop = sports")
#define string312 NSLocalizedString(@"Group Only",@"Optional tag with osm key: group_only")
#define string313 NSLocalizedString(@"Ethiopian",@"Optional value with osm value: ethiopian")
#define string314 NSLocalizedString(@"Burger",@"Optional value with osm value: burger")
#define string315 NSLocalizedString(@"Car Wash",@"POI type with osm tags: amenity = car_wash")
#define string316 NSLocalizedString(@"Lawyer",@"POI type with osm tags: office = lawyer")
#define string317 NSLocalizedString(@"Historic Boundry Stone",@"POI type with osm tags: historic = boundry_stone")
#define string318 NSLocalizedString(@"Yes",@"Optional value with osm value: yes")
#define string319 NSLocalizedString(@"Matress Store",@"POI type with osm tags: shop = bed")
#define string320 NSLocalizedString(@"Gasification",@"Optional value with osm value: gasification")
#define string321 NSLocalizedString(@"Parking Lot",@"Optional value with osm value: parking_lot")
#define string322 NSLocalizedString(@"Bench",@"Optional tag with osm key: bench")
#define string323 NSLocalizedString(@"Phone #",@"Optional tag with osm key: phone")
#define string324 NSLocalizedString(@"Music",@"Optional value with osm value: music")
#define string325 NSLocalizedString(@"Board",@"Optional value with osm value: board")
#define string326 NSLocalizedString(@"Copy and Fax Shop",@"POI type with osm tags: shop = copyshop")
#define string327 NSLocalizedString(@"Method",@"Optional tag with osm key: generator:method")
#define string328 NSLocalizedString(@"Cabin",@"POI type with osm tags: building = cabin")
#define string329 NSLocalizedString(@"Bicycles Repaired",@"Optional tag with osm key: service:bicycle:repair")
#define string330 NSLocalizedString(@"Electric",@"Optional value with osm value: electric")
#define string331 NSLocalizedString(@"Position",@"Optional tag with osm key: fire_hydrant:position")
#define string332 NSLocalizedString(@"Geology",@"Optional value with osm value: geology")
#define string333 NSLocalizedString(@"Rock Shelter",@"Optional value with osm value: rock_shelter")
#define string334 NSLocalizedString(@"Swimming Pool",@"POI type with osm tags: leisure = swimming_pool")
#define string335 NSLocalizedString(@"Dentist",@"POI type with osm tags: amenity = dentist")
#define string336 NSLocalizedString(@"Unorthodox",@"Optional value with osm value: unorthodox")
#define string337 NSLocalizedString(@"Luggage/Bag Shop",@"POI type with osm tags: shop = bag")
#define string338 NSLocalizedString(@"Publicly Visible Clock",@"POI type with osm tags: amenity = clock")
#define string339 NSLocalizedString(@"Center",@"Optional value with osm value: centre")
#define string340 NSLocalizedString(@"Academic",@"Optional value with osm value: academic")
#define string341 NSLocalizedString(@"Takeaway",@"Optional tag with osm key: takeaway")
#define string342 NSLocalizedString(@"Bicycle Pump",@"Optional tag with osm key: service:bicycle:pump")
#define string343 NSLocalizedString(@"Sculpture",@"Optional value with osm value: sculpture")
#define string344 NSLocalizedString(@"Bed and Breakfast",@"POI type with osm tags: tourism = guest_house")
#define string345 NSLocalizedString(@"Anglican",@"Optional value with osm value: anglican")
#define string346 NSLocalizedString(@"Photovoltaic",@"Optional value with osm value: photovoltaic")
#define string347 NSLocalizedString(@"Chinese",@"Optional value with osm value: chinese")
#define string348 NSLocalizedString(@"Buddhist",@"Optional value with osm value: buddhist")
#define string349 NSLocalizedString(@"Frame Store",@"POI type with osm tags: shop = frame")
#define string350 NSLocalizedString(@"Number",@"Optional tag with osm key: addr:housenumber")
#define string351 NSLocalizedString(@"Persian",@"Optional value with osm value: persian")
#define string352 NSLocalizedString(@"College",@"POI type with osm tags: amenity = college")
#define string353 NSLocalizedString(@"Skiing",@"Optional tag with osm key: ski")
#define string354 NSLocalizedString(@"Size",@"Optional tag with osm key: map_size")
#define string355 NSLocalizedString(@"City",@"Optional value with osm value: city")
#define string356 NSLocalizedString(@"Lighthouse",@"POI type with osm tags: man_made = lighthouse")
#define string357 NSLocalizedString(@"Basketball",@"Optional value with osm value: basketball")
#define string358 NSLocalizedString(@"Bus Stop (legacy)",@"POI type with osm tags: highway = bus_stop")
#define string359 NSLocalizedString(@"Tennis",@"Optional value with osm value: tennis")
#define string360 NSLocalizedString(@"Wildlife",@"Optional value with osm value: wildlife")
#define string361 NSLocalizedString(@"Elevator",@"Optional tag with osm key: highway")
#define string362 NSLocalizedString(@"Theater or Opera House",@"POI type with osm tags: amenity = theatre")
#define string363 NSLocalizedString(@"Carpet Store",@"POI type with osm tags: shop = carpet")
#define string364 NSLocalizedString(@"Wood",@"Optional value with osm value: wood")
#define string365 NSLocalizedString(@"Prison",@"POI type with osm tags: amenity = prison")
#define string366 NSLocalizedString(@"Fuel",@"Optional tag with osm key: fuel")
#define string367 NSLocalizedString(@"Beach",@"POI type with osm tags: natural = beach")
#define string368 NSLocalizedString(@"Farm Store",@"POI type with osm tags: shop = farm")
#define string369 NSLocalizedString(@"Animal Shelter",@"POI type with osm tags: amenity = animal_shelter")
#define string370 NSLocalizedString(@"Regional",@"Optional value with osm value: regional")
#define string371 NSLocalizedString(@"Geothermal",@"Optional value with osm value: geothermal")
#define string372 NSLocalizedString(@"Tidal",@"Optional value with osm value: tidal")
#define string373 NSLocalizedString(@"Loans",@"POI type with osm tags: shop = money_lender")
#define string374 NSLocalizedString(@"Cans",@"Optional tag with osm key: recycling:cans")
#define string375 NSLocalizedString(@"Realtor",@"POI type with osm tags: office = estate_agent")
#define string376 NSLocalizedString(@"Lebanese",@"Optional value with osm value: lebanese")
#define string377 NSLocalizedString(@"Tobacco Shop",@"POI type with osm tags: shop = tobacco")
#define string378 NSLocalizedString(@"Car Rental",@"POI type with osm tags: amenity = car_rental")
#define string379 NSLocalizedString(@"Sewing Shop",@"POI type with osm tags: shop = sewing")
#define string380 NSLocalizedString(@"Sidewalk",@"Optional value with osm value: sidewalk")
#define string381 NSLocalizedString(@"Building (residence)",@"Title For Category")
#define string382 NSLocalizedString(@"Limited",@"Optional value with osm value: limited")
#define string383 NSLocalizedString(@"Apartments",@"POI type with osm tags: building = apartments")
#define string384 NSLocalizedString(@"Spring",@"POI type with osm tags: natural = spring")
#define string385 NSLocalizedString(@"Tactile Model",@"Optional value with osm value: tactilve_model")
#define string386 NSLocalizedString(@"Graffiti",@"Optional value with osm value: graffiti")
#define string387 NSLocalizedString(@"Florist",@"POI type with osm tags: shop = florist")
#define string388 NSLocalizedString(@"Travel Agency",@"POI type with osm tags: office = travel_agent")
#define string389 NSLocalizedString(@"Memorial",@"POI type with osm tags: historic = memorial")
#define string390 NSLocalizedString(@"Diesel",@"Optional value with osm value: diesel")
#define string391 NSLocalizedString(@"Max Tents",@"Optional tag with osm key: maxtents")
#define string392 NSLocalizedString(@"Plastic",@"Optional tag with osm key: recycling:plastic")
#define string393 NSLocalizedString(@"Access",@"Optional tag with osm key: access")
#define string394 NSLocalizedString(@"Playground",@"POI type with osm tags: leisure = playground")
#define string395 NSLocalizedString(@"Internet",@"Optional tag with osm key: internet_access")
#define string396 NSLocalizedString(@"Lutheran",@"Optional value with osm value: lutheran")
#define string397 NSLocalizedString(@"Sandwich",@"Optional value with osm value: sandwich")
#define string398 NSLocalizedString(@"Reform",@"Optional value with osm value: reform")
#define string399 NSLocalizedString(@"Gas",@"Optional value with osm value: gas")
#define string400 NSLocalizedString(@"Hackerspace",@"POI type with osm tags: leisure = hackerspace")
#define string401 NSLocalizedString(@"Picnic Site",@"POI type with osm tags: tourism = picnic_site")
#define string402 NSLocalizedString(@"Post Office",@"POI type with osm tags: amenity = post_office")
#define string403 NSLocalizedString(@"Pawn Shop",@"POI type with osm tags: shop = pawnbroker")
#define string404 NSLocalizedString(@"Ice Cream",@"Optional value with osm value: ice_cream")
#define string405 NSLocalizedString(@"Building",@"Optional value with osm value: building")
#define string406 NSLocalizedString(@"Community Center",@"POI type with osm tags: amenity = community_centre")
#define string407 NSLocalizedString(@"Restaurant",@"POI type with osm tags: amenity = restaurant")
#define string408 NSLocalizedString(@"Russian Orthodox",@"Optional value with osm value: russian_orthodox")
#define string409 NSLocalizedString(@"Bakery",@"POI type with osm tags: shop = bakery")
#define string410 NSLocalizedString(@"Voodoo",@"Optional value with osm value: voodoo")
#define string411 NSLocalizedString(@"Volcano",@"POI type with osm tags: natural = volcano")
#define string412 NSLocalizedString(@"Wind",@"Optional value with osm value: wind")
#define string413 NSLocalizedString(@"Note",@"Optional tag with osm key: note")
#define string414 NSLocalizedString(@"Art",@"Optional value with osm value: art")
#define string415 NSLocalizedString(@"Methodist",@"Optional value with osm value: methodist")
#define string416 NSLocalizedString(@"Biomass",@"Optional value with osm value: biomass")
#define string417 NSLocalizedString(@"Social Facilities",@"Title For Category")
#define string418 NSLocalizedString(@"Caravans (RV)",@"Optional tag with osm key: caravans")
#define string419 NSLocalizedString(@"Operator",@"Optional tag with osm key: operator")
#define string420 NSLocalizedString(@"Man Made",@"Title For Category")
#define string421 NSLocalizedString(@"Scrap Metal",@"Optional tag with osm key: recycling:scrap_metal")
#define string422 NSLocalizedString(@"Pharmacy",@"POI type with osm tags: amenity = pharmacy")
#define string423 NSLocalizedString(@"Unitarian",@"POI type with osm tags: religion = unitarian, amenity = place_of_worship")
#define string424 NSLocalizedString(@"Steak House",@"Optional value with osm value: steak_house")
#define string425 NSLocalizedString(@"Alcohol Shop",@"POI type with osm tags: shop = alcohol")
#define string426 NSLocalizedString(@"Underground",@"Optional value with osm value: underground")
#define string427 NSLocalizedString(@"Email",@"Optional tag with osm key: email")
#define string428 NSLocalizedString(@"Office Supplies",@"POI type with osm tags: shop = stationery")
#define string429 NSLocalizedString(@"Movie Theater",@"POI type with osm tags: amenity = cinema")
#define string430 NSLocalizedString(@"Druze",@"Optional value with osm value: druze")
#define string431 NSLocalizedString(@"Permissive",@"Optional value with osm value: permissive")
#define string432 NSLocalizedString(@"Artist",@"Optional tag with osm key: artist_name")
#define string433 NSLocalizedString(@"Bicycles Rented",@"Optional tag with osm key: service:bicycle:rental")
#define string434 NSLocalizedString(@"Country",@"Optional tag with osm key: addr:country")
#define string435 NSLocalizedString(@"Cardboard",@"Optional tag with osm key: recycling:cardboard")
#define string436 NSLocalizedString(@"Bicycle Shop",@"POI type with osm tags: shop = bicycle")
#define string437 NSLocalizedString(@"School",@"POI type with osm tags: amenity = school")
#define string438 NSLocalizedString(@"Comics",@"Optional value with osm value: comics")
#define string439 NSLocalizedString(@"Drinking Water",@"POI type with osm tags: amenity = drinking_water")
#define string440 NSLocalizedString(@"Run of the River",@"Optional value with osm value: run-of-the-river")
#define string441 NSLocalizedString(@"Natural Gass",@"Optional value with osm value: gas")
#define string442 NSLocalizedString(@"Townhall or Cityhall",@"POI type with osm tags: amenity = townhall")
#define string443 NSLocalizedString(@"Pumped-Storage",@"Optional value with osm value: pumped-storage")
#define string444 NSLocalizedString(@"Curtain Store",@"POI type with osm tags: shop = curtain")
#define string445 NSLocalizedString(@"Mennonite",@"Optional value with osm value: mennonite")
#define string446 NSLocalizedString(@"Paper",@"Optional tag with osm key: recycling:paper")
#define string447 NSLocalizedString(@"Aerial Photograph",@"Optional value with osm value: orthophoto")
#define string448 NSLocalizedString(@"Pond",@"Optional value with osm value: pond")
#define string449 NSLocalizedString(@"Fun and Leisure",@"Title For Category")
#define string450 NSLocalizedString(@"Hostel",@"POI type with osm tags: tourism = hostel")
#define string451 NSLocalizedString(@"Fee",@"Optional tag with osm key: fee")
#define string452 NSLocalizedString(@"Capacity",@"Optional tag with osm key: capacity")
#define string453 NSLocalizedString(@"No",@"Optional value with osm value: no")
#define string454 NSLocalizedString(@"Green Waste",@"Optional tag with osm key: recycling:green_waste")
#define string455 NSLocalizedString(@"Guidepost",@"Optional value with osm value: guidepost")
#define string456 NSLocalizedString(@"Biogas",@"Optional value with osm value: biogas")
#define string457 NSLocalizedString(@"Cosmetics",@"POI type with osm tags: shop = chemist")
#define string458 NSLocalizedString(@"Stadium",@"POI type with osm tags: leisure = stadium")
#define string459 NSLocalizedString(@"Ferry Terminal",@"POI type with osm tags: ferry = yes, amenity = ferry_terminal, public_transport = platform")
#define string460 NSLocalizedString(@"Network",@"Optional tag with osm key: network")
#define string461 NSLocalizedString(@"Used",@"Optional tag with osm key: second_hand")
#define string462 NSLocalizedString(@"Hotel",@"POI type with osm tags: tourism = hotel")
#define string463 NSLocalizedString(@"Denomination",@"Optional tag with osm key: denomination")
#define string464 NSLocalizedString(@"Topo",@"Optional value with osm value: topo")
#define string465 NSLocalizedString(@"Smoking",@"Optional tag with osm key: smoking")
#define string466 NSLocalizedString(@"Train Platform (legacy)",@"POI type with osm tags: railway = platform")
#define string467 NSLocalizedString(@"Baptist",@"Optional value with osm value: baptist")
#define string468 NSLocalizedString(@"Retirement Home",@"POI type with osm tags: amenity = social_facility, social_facility = group_home, social_facility:for = senior")
#define string469 NSLocalizedString(@"Fission",@"Optional value with osm value: fission")
#define string470 NSLocalizedString(@"Healthcare",@"Title For Category")
#define string471 NSLocalizedString(@"Castle",@"POI type with osm tags: historic = castle")
#define string472 NSLocalizedString(@"Video Rental",@"POI type with osm tags: shop = video")
#define string473 NSLocalizedString(@"Storage Tank",@"POI type with osm tags: man_made = storage_tank")
#define string474 NSLocalizedString(@"Bicycle",@"Optional tag with osm key: bicycle")
#define string475 NSLocalizedString(@"Office",@"Optional value with osm value: office")
#define string476 NSLocalizedString(@"Wall",@"Optional value with osm value: wall")
#define string477 NSLocalizedString(@"House",@"POI type with osm tags: building = house")
#define string478 NSLocalizedString(@"Bicycle DIY",@"Optional tag with osm key: service:bicycle:diy")
#define string479 NSLocalizedString(@"Parking",@"POI type with osm tags: amenity = parking")
#define string480 NSLocalizedString(@"Billboard",@"Optional value with osm value: billboard")
#define string481 NSLocalizedString(@"Barbecue",@"Optional value with osm value: barbecue")
#define string482 NSLocalizedString(@"Insurance",@"POI type with osm tags: office = insurance")
#define string483 NSLocalizedString(@"Nondenominational",@"Optional value with osm value: nondenominational")
#define string484 NSLocalizedString(@"Informal",@"Optional value with osm value: informal")
#define string485 NSLocalizedString(@"Nuclear",@"Optional value with osm value: nuclear")
#define string486 NSLocalizedString(@"Cemetery",@"POI type with osm tags: landuse = cemetery")
#define string487 NSLocalizedString(@"Lake",@"POI type with osm tags: natural = water")
#define string488 NSLocalizedString(@"Site",@"Optional value with osm value: site")
#define string489 NSLocalizedString(@"Terminal",@"Optional value with osm value: terminal")
#define string490 NSLocalizedString(@"Trash Can",@"POI type with osm tags: amenity = waste_basket")
#define string491 NSLocalizedString(@"Fast Food",@"POI type with osm tags: amenity = fast_food")
#define string492 NSLocalizedString(@"American Football",@"Optional value with osm value: american_football")
#define string493 NSLocalizedString(@"Electronics",@"POI type with osm tags: shop = electronics")
#define string494 NSLocalizedString(@"Map",@"Optional value with osm value: map")
#define string495 NSLocalizedString(@"Art Type",@"Optional tag with osm key: artwork_type")
#define string496 NSLocalizedString(@"Hairdresser",@"POI type with osm tags: shop = hairdresser")
#define string497 NSLocalizedString(@"Type",@"Optional tag with osm key: information")
#define string498 NSLocalizedString(@"Mormon",@"Optional value with osm value: mormon")
#define string499 NSLocalizedString(@"Thermal",@"Optional value with osm value: thermal")
#define string500 NSLocalizedString(@"Supermarket",@"POI type with osm tags: shop = supermarket")
#define string501 NSLocalizedString(@"Drive-through",@"Optional tag with osm key: drive_through")
#define string502 NSLocalizedString(@"Roman Catholic",@"Optional value with osm value: roman_catholic")
#define string503 NSLocalizedString(@"Place of Worship",@"Title For Category")
#define string504 NSLocalizedString(@"Customer",@"Optional value with osm value: customer")
#define string505 NSLocalizedString(@"Orphanage",@"POI type with osm tags: amenity = social_facility, social_facility = group_home, social_facility:for = orphanage")
#define string506 NSLocalizedString(@"Jehovahs Witness",@"Optional value with osm value: jehovahs_witness")
#define string507 NSLocalizedString(@"Public Artwork",@"POI type with osm tags: tourism = artwork")
#define string508 NSLocalizedString(@"Pillar",@"Optional value with osm value: pillar")
#define string509 NSLocalizedString(@"Village",@"Optional value with osm value: village")
#define string510 NSLocalizedString(@"Shower",@"POI type with osm tags: amenity = shower")
#define string511 NSLocalizedString(@"Grave Yard",@"POI type with osm tags: amenity = grave_yard")
#define string512 NSLocalizedString(@"Technology",@"Optional value with osm value: technology")
#define string513 NSLocalizedString(@"Monument",@"POI type with osm tags: historic = monument")
#define string514 NSLocalizedString(@"Wall Loops",@"Optional value with osm value: wall_loops")
#define string515 NSLocalizedString(@"Mexican",@"Optional value with osm value: mexican")
#define string516 NSLocalizedString(@"Government",@"Title For Category")
#define string517 NSLocalizedString(@"Quaker",@"Optional value with osm value: quaker")
#define string518 NSLocalizedString(@"Private",@"Optional value with osm value: private")
#define string519 NSLocalizedString(@"RV Park",@"POI type with osm tags: tourism = caravan_site")
#define string520 NSLocalizedString(@"Glass Bottles",@"Optional tag with osm key: recycling:glass_bottles")
#define string521 NSLocalizedString(@"Street",@"Optional tag with osm key: addr:street")
#define string522 NSLocalizedString(@"Asian",@"Optional value with osm value: asian")
#define string523 NSLocalizedString(@"Used Bikes Sold",@"Optional tag with osm key: service:bicycle:second_hand")
#define string524 NSLocalizedString(@"Pitch",@"POI type with osm tags: leisure = pitch")
#define string525 NSLocalizedString(@"Car Dealership",@"POI type with osm tags: shop = car")
#define string526 NSLocalizedString(@"Analog",@"Optional value with osm value: analog")
#define UPLOADING_STRING NSLocalizedString(@"Uploading",@"Status message infomring user something is being uploaded")
#define SAVING_STRING NSLocalizedString(@"Saving",@"Status message infomring user something is being saved")
#define ERROR_STRING NSLocalizedString(@"Error",@"Status message infomring user there was an error")
#define ZOOM_ERROR_STRING NSLocalizedString(@"Zoom in to load data",@"Status message infomring user they need to zoom in to load data")
#define ZOOM_ALERT_STRING NSLocalizedString(@"You need to zoom in to add a new POI",@"Alert message for user to zoom in on map more to add new POI")
#define OK_STRING NSLocalizedString(@"OK",@"affirmative ok")
#define ZOOM_ALERT_TITLE_STRING NSLocalizedString(@"Zoom Level",@"Title of alert for zoom")
#define FINDING_STRING NSLocalizedString(@"Finding",@"Message to User alerting that the app is parsing or finding the nodes/ways/relations")
#define DOWNLOAD_ERROR_STRING NSLocalizedString(@"Download Error",@"Error shown to user that error downloading existing data")
#define SETTINGS_TITLE_STRING NSLocalizedString(@"Settings",@"title for view where settings can be changed")
#define BING_AERIAL_STRING NSLocalizedString(@"Bing Aerial",@"Setting to select background layer")
#define MAPQUEST_AERIAL_STRING NSLocalizedString(@"OpenMapquest Aerial",@"Setting to select background layer")
#define OSM_DEFAULT_STRING NSLocalizedString(@"OSM Default",@"Setting to select background layer")
#define NO_NAME_HIGHWAY_STRING NSLocalizedString(@"Show No Name Streets",@"Setting to show or hide streets or highways with no names")
#define LOGIN_STRING NSLocalizedString(@"Login to OpenStreetMap",@"Login button label")
#define LOGOUT_STRING NSLocalizedString(@"Logout of OpenStreetMap",@"Logout button label")
#define FEEDBACK_STRING NSLocalizedString(@"Feedback",@"label for feedback button")
#define ABOUT_STRING NSLocalizedString(@"About POI+",@"label for about button")
#define TILE_SOURCE_STRING NSLocalizedString(@"Tile Source",@"Section label for tile source setting")
#define REMOVE_STRING NSLocalizedString(@"Remove",@"Button label to remove tag")
#define CANCEL_STRING NSLocalizedString(@"Cancel",@"Button label to cancel action")
#define DELETE_STRING NSLocalizedString(@"Delete",@"Button label to delete item")
#define DELETE_ALERT_TITLE_STRING NSLocalizedString(@"Delete Point of Interest",@"Title to aler to delete node")
#define DELETE_ALERT_STRING NSLocalizedString(@"Are you Sure you want to delete this node?",@"Message when deleting a node")
#define DELETING_STRING NSLocalizedString(@"Deleting",@"Message to user while deleting node")
#define INFO_TITLE_STRING NSLocalizedString(@"Info",@"Title for detailed view of node")
#define SAVE_STRING NSLocalizedString(@"Save",@"Button label to save any changes")
#define NAME_STRING NSLocalizedString(@"Name",@"Label for name")
#define CATEGORY_STRING NSLocalizedString(@"Category",@"Label for category")
#define TYPE_STRING NSLocalizedString(@"Type",@"Label for type")
#define NO_NAME_STRING NSLocalizedString(@"No Name Street",@"label for street with missing name tag")
#define LOCA_DATA_STRING NSLocalizedString(@"Local Data",@"Button label for signifying using local or downloaded data")
